# PART 1 : PANDAS 

Q1 : Create a DataFrame df with columns ‘Std_Name’, ‘Roll_no’, and ‘CPI’. Write a code to
create a new DataFrame containing only rows where the value in column ‘CPI’ is greater than
60. Also calculate the overall mean, median, and standard deviation.

In [2]:
import pandas as pd

df = pd.DataFrame({'Std_Name': ['Alex', 'Bob', 'Claire'], 
                   'Roll_no': [1, 2, 3], 
                   'CPI': [65, 55, 75]})

new_df = df[df['CPI'] > 60]

mean = df['CPI'].mean() 
median = df['CPI'].median()
std = df['CPI'].std()

print(new_df)
print(mean, median, std)

  Std_Name  Roll_no  CPI
0     Alex        1   65
2   Claire        3   75
65.0 65.0 10.0


In [79]:
df = pd.DataFrame({'Subjects': ['Math', 'Physics', 'Chemistry', 'Math', 'Physics'],  
                   'Book_Authors': ['Author1', 'Author2', 'Author3', 'Author4', 'Author5'],
                   'No_of_Books': [5, 3, 2, 4, 5]})
                   
subject_counts = df.groupby('Subjects')['No_of_Books'].sum()

print(subject_counts)

Subjects
Chemistry    2
Math         9
Physics      8
Name: No_of_Books, dtype: int64


In [3]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Claire', 'Dan'],
                   'Age': [17, 21, 33, 41],  
                   'Salary': [-1000, 2000, 3000, 4000]})
                   
df = df[(df['Age']>=18) & (df['Salary']>=0)]

print(df)

     Name  Age  Salary
1     Bob   21    2000
2  Claire   33    3000
3     Dan   41    4000


In [4]:
time_df = pd.DataFrame({'TimeStamp': ['2023-02-01 14:35:00', 
                                      '2023-02-03 06:15:30',
                                      '2023-02-05 23:48:45']})

time_df['TimeStamp'] = pd.to_datetime(time_df['TimeStamp'])  
time_df['Hour'] = time_df['TimeStamp'].dt.hour

print(time_df)

            TimeStamp  Hour
0 2023-02-01 14:35:00    14
1 2023-02-03 06:15:30     6
2 2023-02-05 23:48:45    23


# NumPy application 

In [2]:
import numpy as np 
import time

In [82]:
arr_1 = np.random.rand(106, 104)
arr_2 = np.random.rand(106, 104)

arr_temp = arr_2.T 

# Using Loops 
start = time.time()
result_loop = np.zeros((106, 106))
for i in range(len(arr_1)):
    for j in range(len(arr_temp)):
        for k in range(len(arr_2[0])):
            result_loop[i][j] += arr_1[i][k] * arr_temp[k][j] 
end = time.time()
t1 = end - start

In [83]:
# Vectorized 
start = time.time()
result_vectorized = np.dot(arr_1, arr_2.T)  
end = time.time()
t2 = end - start

speedup = t1 / t2

In [84]:
print("Time using loops:", t1)
print("Time using vectorized operation:", t2)
print("Speed up:", speedup)

Time using loops: 0.4839138984680176
Time using vectorized operation: 0.026470184326171875
Speed up: 18.28147067300764


In [85]:
arr1 = np.arange(30).reshape(5,6)
print(arr1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [86]:
second_col = arr1[:,1]
last_row  =arr1[-1:]

print(second_col)
print(last_row)

[ 1  7 13 19 25]
[[24 25 26 27 28 29]]


In [42]:
arr_Q3 = np.random.randint(0,10,size=(5,6))
print(arr_Q3)

[[0 4 1 8 1 9]
 [3 5 2 3 9 3]
 [8 7 5 6 0 7]
 [8 2 0 7 6 6]
 [6 5 6 0 1 8]]


In [75]:
flattened_array = arr_Q3.flatten()
unique_ele, counts = np.unique(flattened_array,return_counts=True)

In [70]:
resultant_freq = dict(zip(unique_ele,counts)) 
print(resultant_freq)

{0: 4, 1: 3, 2: 2, 3: 3, 4: 1, 5: 3, 6: 5, 7: 3, 8: 4, 9: 2}


In [61]:
# Generate random coefficient matrix A and vector b
A = np.random.rand(5,5)  
b = np.random.rand(5)

x = np.linalg.solve(A, b)

print("Coefficient Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nSolution vector x:")
print(x)

Coefficient Matrix A:
[[0.57542795 0.33375649 0.84887775 0.45633653 0.97218802]
 [0.56723268 0.07296954 0.45099471 0.55402018 0.4114571 ]
 [0.01735305 0.26220376 0.6062187  0.50132686 0.65472093]
 [0.07161075 0.61739989 0.49820819 0.69698711 0.22484608]
 [0.27520825 0.86582439 0.5857965  0.85299653 0.94121136]]

Vector b:
[0.55701099 0.55375767 0.67072526 0.55706513 0.24017393]

Solution vector x:
[-0.36730496 -0.76605962  1.24829493  0.74843119 -0.38792947]


In [77]:
arr_Q5 = np.array([85, 92, 75, 85, 90, 92, 85, 75, 85, 92, 75, 85, 90, 92, 85, 75, 85, 92])

freq_85 = np.sum(arr_Q5 == 85)

print(freq_85)

7
